### ISSUE TITLE
Using shirley and tougaard background Error 

### ISSUE THREAD

**Issue by SunC0der** [Julian-Hochhaus/lmfit-additional-models#2]
Hi Julian,

I tried to implement your background function "ShirleyBG"  into a small python script getting a "KeyError: 'y' " no matter whether I use a pandas.Series nor a array for my Intensity values. 
Any ideas what could cause the problem ? I exchanged the background function with a lmfit.LinearModel and that worked, so I assume that y has the correct format for lmfit. 

Thank you in advance

Best,
Max

Script:
```python
# Load Packages: 

import sys
sys.path.append(
    "path/to/lmfit-additional-models"
)
from models import ShirleyBG
from lmfit.models import VoigtModel

import pandas as pd
import matplotlib.pyplot as plt



# Load and label data:
data_path = (
    "/path/to/data/data_file.csv"
)

data = pd.read_csv(
    data_path,
    sep="\t",
    header=None,
)

data.columns = ["Energy [eV]", "Intensity [a.u.]"]
x = data.loc[:, "Energy [eV]"]
y = data.loc[:, "Intensity [a.u.]"]

# lmfit 

# Define models
background_model = ShirleyBG()
data_model = VoigtModel()

combined_model = data_model - background_model

# Define parameters
params = combined_model.make_params()
params.update(background_model.guess(y, x=x))
params.update(data_model.guess(y, x=x))

# Fit 
result = combined_model.fit(y, params, x=x) # <- The error is thrown 

# Display final results 
print(result.fit_report())

plt.scatter(x, y, s=1, c="tab:green")
plt.plot(x, result.init_fit, "--", label="initial fit")
plt.plot(x, result.best_fit, "-", label="best fit")
plt.legend()
``` 

Error message: 
```python

  File /usr/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/path/to/lmfit_practice.py:70
    result = combined_model.fit(y, params, x=x)

  File /usr/lib/python3.11/site-packages/lmfit/model.py:1060 in fit
    if not np.isscalar(kwargs[var]):

KeyError: 'y'
``` 

Data: 

[data_file.csv](https://github.com/Julian-Hochhaus/lmfit-additional-models/files/11533508/data_file.csv)

**Comment by Julian-Hochhaus** [comment]
```
import sys
sys.path.append(
    "path/to/lmfit-additional-models"
)
from models import ShirleyBG
from lmfit.models import VoigtModel
import numpy as np # had to import numpy too
import pandas as pd
import matplotlib.pyplot as plt



# Load and label data:
data_path = (
    "data_file.csv"
)

data = pd.read_csv(
    data_path,
    sep="\t",
    header=None,
)

data.columns = ["Energy [eV]", "Intensity [a.u.]"]
x = data.loc[:, "Energy [eV]"]
y = data.loc[:, "Intensity [a.u.]"]

# lmfit 

# Define models
background_model = ShirleyBG(independent_vars=['y']) #added independent_vars=['y'] due to the shirley needing a different independent variable than the default x
data_model = VoigtModel()

combined_model = data_model + background_model #changed '-' to '+', because your data contain background +data, model needs to reflect that, background is included in the model and fit and not removed before fitting

# Define parameters
params = combined_model.make_params()
params.update(background_model.guess(y, x=x))
params.update(data_model.guess(y, x=x))
# Fit 
result = combined_model.fit(y, params, x=x, y=y) # <- The error is thrown #you need to pass all independent variables explicitly to the Model.fit() function

# Display final results 
print(result.fit_report())

plt.scatter(x, y, s=1, c="tab:green")
plt.plot(x, result.init_fit, "--", label="initial fit")
plt.plot(x, result.best_fit, "-", label="best fit")
plt.legend()
```
In this code, I have made the following changes:

- Added the numpy import, which was missing.
- Updated the` combined_model `definition to use the `+` operator instead of `-` to reflect the combination of the data and background models.
- Passed the independent_vars explicitly to the Shirley-model, because they differ from default value `x` by  changing the `background_model` to `background_model = ShirleyBG(prefix='bg_', independent_vars=['y'])`
- Fixed the `result = combined_model.fit(y, params, x=x)` line to pass all independent variables explicitly by changing it to `result = combined_model.fit(y, params, x=x, y=y)` .



If you want to access the components of the model individually, you need to add prefixes to the models in addition.

e.g.:
- Modify the background_model instantiation to include the` prefix='bg_'` argument to distinguish the background model parameters. 

- Calculate the background afterward using `result.eval_components()['bg_']` to extract the background component from the fit.

Now, you can plot for example the result with substracted background: 

```
plt.plot(x, result.best_fit-bg,  "-", label="best fit-bg")
plt.legend()
plt.show()
plt.clf()
```
Fit seems solid, speed could be improved further with better starting parameters for the Shirley model.
(Currently: 32sec/100 calls of calculating the result)

By adding 

`params.add("bg_const", value=min(y))`

I was able to decrease the execution time by roughly 50% to  16.5sec/100 calls.

I hope that helps so far :)
