### ISSUE TITLE
Peak area ratio as a fit constraint possible ? 

### ISSUE THREAD

**Issue by SunC0der** [Julian-Hochhaus/lmfit-additional-models#3]
Hi,

I was wondering whether it is possible with your code / lmfit generally to impose area ratio constrains between functions ? 
I could put constrains on the amplitude and on the fwhm of the functions, however due to effects like the Super Coster–Kronig
effect (https://en.wikipedia.org/wiki/Coster%E2%80%93Kronig_transition) the FWHM can sometimes differ between coupled peaks. Thus I would like to keep amplitude and FWHM flexible, while keeping the area ratio constant between the peaks.

**Comment by Julian-Hochhaus** [comment]
As long as you are using symmetric peaks, it is possible. The models I have introduced however all allow asymmetry and for asymmetric peaks, the area is not well-defined and infinite.

But, generally in lmfit, the amplitude corresponds to the area and not the peak height. Most models contain a height parameter, which is the actual amplitude. Fitting a Voigt to normed data, e.g. results in:

```
[[Variables]]
    data_amplitude:  1.48463916 +/- 8.1221e-10 (0.00%) (init = 2.409795)
    data_center:     603.702293 +/- 2.0501e-10 (0.00%) (init = 603.7064)
    data_sigma:      0.30984505 +/- 1.6390e-10 (0.00%) (init = 0.353535)
    bg_k:           -1.5803e-12 +/- 3.1827e-12 (201.40%) (init = 0.0003)
    bg_const:        4.7909e-10 +/- 2.7224e-10 (56.83%) (init = 0.01542547)
    data_gamma:      0.30984505 +/- 1.6390e-10 (0.00%) == 'data_sigma'
    data_fwhm:       1.11584207 +/- 5.9025e-10 (0.00%) == '1.0692*data_gamma+sqrt(0.8664*data_gamma**2+5.545083*data_sigma**2)'
    data_height:     1.00004171 +/- 3.3328e-10 (0.00%) == '(data_amplitude/(max(1e-15, data_sigma*sqrt(2*pi))))*wofz((1j*data_gamma)/(max(1e-15, data_sigma*sqrt(2)))).real'
```

As you may see, the height is 1 and the expression on which height is limited, ( `height='(data_amplitude/(max(1e-15, data_sigma*sqrt(2*pi))))*wofz((1j*data_gamma)/(max(1e-15, data_sigma*sqrt(2)))).real' `), is the[ Faddeeva function which is the evaluated Voigt integral](https://en.wikipedia.org/w/index.php?title=Voigt_profile&oldid=1152849918).

Therefore you can simply put a constraint on the amplitude for all models without an asymmetry to constrain the area.

For asymmetric peaks, the problem is not easy to solve due to the infinite integral, I tested some approximations, but they were not satisfying for all cases. However, you could afterward calculate the area under the asymmetric peaks over the measured data and compare them, but these areas are not accessible to the fit model because the area could only be calculated after fitting using the Model_Result.
